In [1]:
import numpy as np

In [2]:
y_pred =  np.array([1,1,0,0,1])
y_train = np.array([0.3,0.7,1,0,0.5])

### Mean Absolute Error

In [3]:
def mae(y_pred, y_train):
    total_error = 0
    for yp, yt in zip(y_pred, y_train):
        total_error += abs(yp - yt)
    print("Total error is:",total_error)
    mae = total_error/len(y_pred)
    print("Mean absolute error is:",mae)
    return mae

In [5]:
mae(y_pred,y_train)

Total error is: 2.5
Mean absolute error is: 0.5


0.5

#### Using numpy

In [8]:
def mae_np(y_pred, y_train):
    return np.mean(np.abs(y_pred-y_train))

In [10]:
mae_np(y_pred, y_train)

0.5

### Mean Squared Error

In [11]:
def mse(y_pred, y_train):
    total_error = 0
    for yp, yt in zip(y_pred, y_train):
        total_error += (yp - yt)*(yp - yt)
    print("Total error is:",total_error)
    mse = total_error/len(y_pred)
    print("Mean squared error is:",mse)
    return mse

In [12]:
mse(y_pred,y_train)

Total error is: 1.83
Mean squared error is: 0.366


0.366

In [13]:
### Using numpy

In [23]:
def mse_np(y_pred,y_train):
    return np.mean(np.square(y_pred-y_train))

In [24]:
mse_np(y_pred,y_train)

0.366

### Log Loss or Binary Cross Entropy

In [25]:
np.log([0])

/home/navjot/.local/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([-inf])

In [30]:
epsilon = 1e-15

In [31]:
np.log([1e-15])

array([-34.53877639])

In [32]:
y_pred

array([1, 1, 0, 0, 1])

In [37]:
y_pred_new = [max(i,epsilon) for i in y_pred]
y_pred_new

[1, 1, 1e-15, 1e-15, 1]

In [38]:
y_pred_new = [min(i,1-epsilon) for i in y_pred_new]
y_pred_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [39]:
y_pred_new = np.array(y_pred_new)

In [40]:
np.log(y_pred_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [41]:
np.mean(y_train*np.log(y_pred_new)+(1-y_train)*np.log(1-y_pred_new))

-17.2696280766844

In [46]:
def log_loss(y_train, y_pred):
    y_pred_new = [max(i,epsilon) for i in y_pred]
    y_pred_new = [min(i,1-epsilon) for i in y_pred_new]
    y_pred_new = np.array(y_pred_new)
    return -np.mean(y_train*np.log(y_pred_new)+(1-y_train)*np.log(1-y_pred_new))

In [47]:
log_loss(y_train, y_pred)

17.2696280766844